framework:
    secret: '%env(APP_SECRET)%'

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto' ]
    serializer:
        enabled: true

when@test:
    framework:
        test: true
