security:
    password_hashers:
        App\Domain\User\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\Entity\User

                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/(docs|swagger|admin|docs\.jsonld), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/time_entries, roles: IS_AUTHENTICATED_FULLY }
