security:
    password_hashers:
        App\Domain\User\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\Entity\User

                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(docs|swagger|admin|docs\.jsonld), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/time_entries, roles: IS_AUTHENTICATED_FULLY }
