name: Build and Deploy API

on:
  push:
    branches:
      - master

env:
  PHP_IMAGE_NAME: bhacas/timetrack-php:latest
  WEB_IMAGE_NAME: bhacas/timetrack-nginx:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $PHP_IMAGE_NAME -f .docker/Dockerfile --target=php-prod ./
          docker push $PHP_IMAGE_NAME
          docker build -t $WEB_IMAGE_NAME -f .docker/Dockerfile --target=nginx-prod ./
          docker push $PHP_IMAGE_NAME

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: bartek
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/timetrack
            docker compose pull
            docker compose up -d --force-recreate
