name: Build and Deploy API

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: bhacas/timetrack-api:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME ./
          docker push $IMAGE_NAME

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: bartek
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/timetrack
            docker compose pull
            docker compose up -d --force-recreate
